apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-platform-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
    - ml-platform
  selector:
    matchLabels:
      app: ml-inference
  endpoints:
  - port: http
    path: /metrics
    interval: 15s